### ISSUE TITLE
Modpack Updater only pulls from the standard .minecraft folder.

### ISSUE THREAD

**Issue by GenerelSchwerz** [KarmaConfigs/ModpackUpdater#2]
Hey, the modpackupdater won't download from this directory: C:\Users\rocco\Twitch\Minecraft\Instances\Spooky Minecraft

![image](https://user-images.githubusercontent.com/43506958/91307998-aa755a80-e77c-11ea-958a-9625f526634f.png)

The directory and everything was set through the creator panel. 

![image](https://user-images.githubusercontent.com/43506958/91308073-c5e06580-e77c-11ea-8e05-81f86049137f.png)

It's detecting my standard .minecraft folder.

**Comment by KarmaDeb** [comment]
I found why this is happening, I'll release a fix for it soon
